name: DiscordSync
version: '1.0'
main: br.com.ylorde.Main
api-version: '1.21'
load: STARTUP
authors: [ "yLorde", "Luccas Person" ]
description: Plugin feito para conectar o Discord ao minecraft
website: https://www.ylorde.com.br
